#include "gamedata.h"

std::unordered_map<char, std::string> characters = {
        {0, "Mario"},
        {1, "Luigi"},
        {2, "DK"},
        {3, "Diddy"},
        {4, "Peach"},
        {5, "Daisy"},
        {6, "Yoshi"},
        {7, "Baby Mario"},
        {8, "Baby Luigi"},
        {9, "Bowser"},
        {10, "Wario"},
        {11, "Waluigi"},
        {12, "Koopa(G)"},
        {13, "Koopa(R)"},
        {14, "Toad(R)"},
        {15, "Toad(B)"},
        {16, "Toad(Y)"},
        {17, "Toad(G)"},
        {18, "Toad(P)"},
        {19, "Boo"},
        {20, "Toadette"},
        {21, "Shy Guy(R)"},
        {22, "Shy Guy(B)"},
        {23, "Shy Guy(Y)"},
        {24, "Shy Guy(G)"},
        {25, "Shy Guy(Bk)"},
        {26, "Birdo"},
        {27, "Monty"},
        {28, "Bowser Jr"},
        {29, "Paratroopa(R)"},
        {30, "Paratroopa(G)"},
        {31, "Pianta(B)"},
        {32, "Pianta(R)"},
        {33, "Pianta(Y)"},
        {34, "Noki(B)"},
        {35, "Noki(R)"},
        {36, "Noki(G)"},
        {37, "Hammer Bro"},
        {38, "Boomerang Bro"},
        {39, "Fire Bro"},
        {40, "Toadsworth"},
        {41, "Magikoopa(B)"},
        {42, "Magikoopa(R)"},
        {43, "Magikoopa(G)"},
        {44, "Magikoopa(Y)"},
        {45, "King Boo"},
        {46, "Petey"},
        {47, "Dixie"},
        {48, "Goomba"},
        {49, "Paragoomba"},
        {50, "Dry Bones(Gy)"},
        {51, "Dry Bones(G)"},
        {52, "Dry Bones(B)"},
        {53, "Dry Bones(R)"}
};

std::unordered_set<char> captains = {0,1,2,3,4,5,6,9,10,11,17,19};

std::vector<std::unordered_set<char>> duplicates = {
        {12,13},
        {14,15,16,17,18},
        {21,22,23,24,25},
        {29,30},
        {31,32,33},
        {34,35,36},
        {37,38,39},
        {41,42,43,44},
        {50,51,52,53}
};
